//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace helalinden_dev1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Foto
    {
        public int FotoId { get; set; }
        public int AracFotoId { get; set; }
        public string Fotolar { get; set; }
    
        public virtual Araclar Araclar { get; set; }
    }
}
