//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace helalinden_dev1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kiralama
    {
        public int KiraId { get; set; }
        public System.DateTime KiraTarih { get; set; }
        public string KiraSure { get; set; }
        public int KiraUyeId { get; set; }
        public int KiraUcret { get; set; }
    
        public virtual Araclar Araclar { get; set; }
        public virtual Uyeler Uyeler { get; set; }
    }
}
